trip_purpose_list: ['All', 'Change Mode Inserted Purpose', 'Escort', 
'Meal', 'None/Home', 'Personal Business', 'School', 'Shop', 'Social', 'Work']

person_type_list: ['All', 'Child Age 0-4', 'Child Age 5-15', 'Full-Time Worker', 
'High School Student Age 16+', 'Non-Working Adult Age <65', 
'Non-Working Adult Age 65+', 'Part-Time Worker', 'University Student']

district_list: ['All', 'East Side', 'Everett-Lynwood-Edmonds', 'Kitsap', 
'North Seattle-Shoreline', 'Renton-FedWay-Kent', 'S.Kitsap', 'Seattle CBD', 
'South Pierce', 'Suburban Snohomish', 'Tacoma', 'West-South Seattle']

mode_list: ['All','Walk','Bike','SOV','HOV2','HOV3+','School Bus',
'Transit','Other']

county_list: ['All','King','Kitsap','Pierce','Snohomish']

agency_list: ['All','King County Metro', 'Sound Transit','Pierce Transit','Everett Transit',
             'Community Transit', 'Kitsap Transit','Washington Ferries']

transit_mode_list: ['commuter_rail','ferry','litrat','passenger_ferry','trnst']

transit_line_dict:
 '118331': 'E Line SB'
 '119150': 'Link NB'
 '119166': 'Sounder NB'
 '118355': 'Metro 40 SB'
 '118332': 'WSF Bainbridge to Seattle'
 '118342': 'WSF Bremerton to Seattle'
 '118363': 'Passenger Ferry Bremerton to Seattle'
 '118585': 'Passenger Ferry Vashon Island to Seattle'
 '118225': 'Passenger Ferry West Seattle to Seattle'
 '118337': 'C Line to Downtown Seattle' 